### ISSUE TITLE
구현 목표

### ISSUE THREAD

**Issue by yusa-imit** [Coffee-namu/ansim-restaurant-server#1]
- [x] DB연동
- [x] 유저 위치 기반 식당 추천 시스템 개발
- [x] 게시판 기능 개발
- [x] 로그인/회원가입/탈퇴

**Comment by ucyang** [comment]
로그인/회원가입 기능 구현 완료했습니다.

그러나 회원 탈퇴 기능은 필수가 아니기에 후순위로 미뤄두겠습니다.

**Comment by ucyang** [comment]
개발 완료 후 이슈를 닫습니다.
